version: 0.2
phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed sucessfully
artifacts:
  files:
    - target/aws-java1-0.0.1-SNAPSHOT.ja
  discard-paths: yes
